- metanorm/handlers.py
- metanorm/normalizers/geospatial_defaults.py
- metanorm/normalizers/sentinel1_identifier.py
- metanorm/normalizers/sentinel_safe.py
- tests/normalizers/test_sentinel1_identifier.py
In order to pass the tests of harvesting this modifications must be made in the normalizer. New test is added to harvesting repo. That test alongside others, require this changes.
> #9 default values for dataset_parameter is set//names are changed in the tests

- metanorm/normalizers/radarsat2_csv.py
- tests/normalizers/test_radarsat2_csv.py
Fixes #26 
Adds new normalizer and tests
> Issue26 radarsat2 csv

- metanorm/normalizers/url.py
- tests/normalizers/test_url.py
The begging of regex of osisaf must be corrected!
> #33 one regex pattern corrected

- metanorm/normalizers/url.py
- tests/normalizers/test_url.py
> Fix time coverage mistakes in the URL normalizer 

- metanorm/normalizers/acdd.py
- metanorm/normalizers/netcdf_cf.py
- metanorm/normalizers/sentinel_safe.py
- metanorm/normalizers/url.py
- metanorm/utils.py
- tests/normalizers/test_acdd.py
- tests/normalizers/test_sentinel_safe.py
- tests/normalizers/test_url.py
- tests/test_utils.py
Resolves #43.
I limited the modifications to the products necessary for TOPVOYS.
> Add information in the summary field

- metanorm/normalizers/url.py
- tests/normalizers/test_url.py
Resolves #39 
:warning: Needs to be merged after #45
> Add IBI_ANALYSIS_FORECAST_PHYS_005_001 to the URL normalizer

- tests/normalizers/test_url.py
Resolves #47 
:warning: Needs to be merged after #46
> Write dataset parameters once in the url normalizer tests

- .gitignore
- metanorm/handlers.py
- metanorm/normalizers/creodias.py
- metanorm/normalizers/sentinel_safe.py
- tests/normalizers/test_creodias.py
> Add Creodias API normalizer

- metanorm/normalizers/url.py
- tests/normalizers/test_url.py
> Update provider for remss.com

- .travis.yml
- docker/Dockerfile_tests
Resolves #57 
Also switched to the slim nansat_base image for tests.
> Update the test image

- .travis.yml
- metanorm/normalizers/url.py
- tests/normalizers/test_acdd.py
- tests/normalizers/test_creodias.py
- tests/normalizers/test_sentinel1_identifier.py
- tests/normalizers/test_sentinel_safe.py
- tests/normalizers/test_url.py
> Add HYCOM (FTP) to URL normalizer

- metanorm/normalizers/url.py
- tests/normalizers/test_url.py
> Add product info to the CCI Climatology summary

- metanorm/handlers.py
- metanorm/normalizers/cmems_in_situ_tac.py
- metanorm/normalizers/netcdf_cf.py
- tests/normalizers/test_cmems_in_situ_tac.py
Resolves #54 
I did not find a way to makes this a generic normalizer and had to use the "id matching" technique.
> Add a normalizer for CMEMS in situ TAC datasets

- metanorm/normalizers/cmems_in_situ_tac.py
- tests/normalizers/test_cmems_in_situ_tac.py
> Fix CMEMS in situ TAC summary

- metanorm/normalizers/cmems_in_situ_tac.py
- tests/normalizers/test_cmems_in_situ_tac.py
> Add support for CMEMS INSITU_GLO_UV_NRT_OBSERVATIONS_013_048 product

- metanorm/normalizers/sentinel_safe.py
- tests/normalizers/test_sentinel_safe.py
> Adapt Sentinel SAFE normalizer after scihub URL change

- README.md
- metanorm/normalizers/url.py
- tests/normalizers/test_url.py
> Add support for RTOFS

- metanorm/utils.py
- tests/test_utils.py
> Keyword translation for GCMD platforms

- metanorm/normalizers/sentinel_safe.py
@akorosov 
I have talked to @aperrin66  for the design of code. It is agreed that we develop the new field as a subsection of description section of summary.
> #74 one extra field which is needed for colhub

- metanorm/handlers.py
- metanorm/normalizers/creodias.py
- metanorm/normalizers/earthdata_cmr.py
- metanorm/utils.py
- tests/normalizers/test_earthdata_cmr.py
> Add support for Earthdata CMR search API

- metanorm/normalizers/url.py
- tests/normalizers/test_url.py
> Update IBI_ANALYSISFORECAST_PHY_005_001in URL normalizer

- metanorm/normalizers/url.py
- tests/normalizers/test_url.py
> Update MEDSEA_ANALYSISFORECAST_PHY_006_013 in URL normalizer

- metanorm/normalizers/geospaas/noaa_rtofs.py
- metanorm/normalizers/url.py
- tests/normalizers/test_noaa_rtofs.py
- tests/normalizers/test_url.py
> Create noaa rtofs normalizer

- metanorm/normalizers/geospaas/noaa_hycom.py
- metanorm/normalizers/url.py
- tests/normalizers/test_noaa_hycom.py
- tests/normalizers/test_url.py
> Create hycom normalizer

- metanorm/normalizers/geospaas/gportal_gcom.py
- metanorm/normalizers/url.py
- tests/normalizers/test_gportal_gcom.py
- tests/normalizers/test_url.py
> Create GPortal GCOM normalizer

- metanorm/normalizers/geospaas/ceda_esa_cci.py
- metanorm/normalizers/url.py
- tests/normalizers/test_ceda_esa_cci.py
- tests/normalizers/test_url.py
> Create a ESA CCI climatology normaliser

- metanorm/normalizers/geospaas/podaac.py
- metanorm/utils.py
- setup.py
- tests/normalizers/test_podaac.py
> Deal with PODAAC coverage crossing the IDL

- metanorm/normalizers/geospaas/aviso.py
- metanorm/normalizers/geospaas/cmems_in_situ_tac.py
- metanorm/normalizers/geospaas/cpom.py
- metanorm/normalizers/geospaas/nextsim.py
- tests/normalizers/data.py
- tests/normalizers/test_aviso.py
- tests/normalizers/test_cmems_in_situ_tac.py
- tests/normalizers/test_cpom.py
- tests/normalizers/test_nextsim.py
Resolves #121 
Requires https://github.com/nansencenter/django-geo-spaas-harvesting/pull/123 in harvesting
> Nextsim normalizer

- metanorm/normalizers/geospaas/cmems.py
- tests/normalizers/test_cmems.py
> Add CMEMS 001_027 and  001_028

- metanorm/normalizers/geospaas/creodias.py
> Use ESA/EO as default Creodias provider

- metanorm/normalizers/geospaas/creodias.py
- tests/normalizers/test_creodias.py
for new download URLs
Resolves #133
> update creodias normalizer check

- metanorm/normalizers/geospaas/resto.py
- tests/normalizers/test_resto.py
Generalize Creodias normalizer to support resto APIs in general, and Copernicus Data Space's resto API in particular.
> Upgrade creodias normalizer

- metanorm/normalizers/geospaas/gportal_gcom.py
- tests/normalizers/test_gportal_gcom.py
Update Gportal AMSR2 normalizer to support products other than level 3 SST.
> Generalize GPortal AMSR2 normalizer

- metanorm/normalizers/geospaas/amsr2_asi.py
- metanorm/normalizers/geospaas/nextsim.py
- tests/normalizers/test_amsr2_asi.py
> Add support for uni bremen's AMSR2 sea ice concentration
